SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

STARTING_TEXT = "Hello PLayer!!! Press the space bar to start."
def ENDING_TEXT(x):
    return f"GAME OVER! YOU SCORED {x} POINTS!!!"

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_NUMBER = 50

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
PLAYER_SHOOT_COOLDOWN = 0.5
PLAYER_IMMUNE_TIME = 1